nodeLinker: node-modules

npmMinimalAgeGate: 7

npmPublishAccess: restricted

npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  nigelng:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN}'
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.17.0.cjs
